### ISSUE TITLE
Does it work

### ISSUE THREAD

**Issue by Funktionar** [bananaturtlesandwich/UE4-Map-Editor#4]
I'm failing to compile the code, does this project work at all?

**Comment by bananaturtlesandwich** [comment]
It should be in a working state but you may have a dependency problem
![image](https://user-images.githubusercontent.com/71292624/189534795-8ed7f7a3-e6c4-4511-b470-28c981292685.png)
did you migrate the packages as suggested in the readme?

**Comment by bananaturtlesandwich** [comment]
However I haven't worked on it in a while because I want to improve my understanding of OpenGL as a whole. I think only transform editing works

**Comment by bananaturtlesandwich** [comment]
Ah just checked I was in the middle of a refactor on this. It will build if your dependencies are fine but nothing is actually functional so not much point

**Comment by Funktionar** [comment]
Okay, thank you.
